import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import "./globals.css";
import { borel, pt } from "./ui/fonts";


export const metadata: Metadata = {
  title: "Emirhan's Blog",
  description: "Generated by next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${pt.className}`}
      >
        {children}
      </body>
    </html>
  );
}
