import type { Metadata } from "next";
import "./globals.css";
import { pt } from "./ui/fonts";
import AuthSessionProvider from "./components/SessionProvider";


export const metadata: Metadata = {
  title: "Emirhan's Blog",
  description: "Generated by next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${pt.className}`}
      >
        <AuthSessionProvider>
          {children}
        </AuthSessionProvider>
      </body>
    </html>
  );
}
